/** Terjemahan jabatan staf untuk mode English (dipakai di /tentang dan /gurustaffsmk). */
export const JABATAN_EN: Record<string, string> = {
  'Ketua BPH': 'Chair of the Foundation Board',
  'Advisor BPH': 'Foundation Board Advisor',
  'Wakil Ketua BPH': 'Vice Chair of the Foundation Board',
  'Ketua Komite': 'School Committee Chair',
  'Kepala SMK Citra Negara': 'Principal of SMK Citra Negara',
  'Waka Kurikulum': 'Vice Principal of Curriculum',
  'Kaprog TJKT': 'Head of TJKT Program',
  'Kaprog DKV': 'Head of DKV Program',
  'Kaprog PM': 'Head of PM Program',
  'Kaprog PPLG & BKK': 'Head of PPLG Program & Career Center',
  'Kaprog MPLB': 'Head of MPLB Program',
  'BK & Piket Gedung A': 'Counselor & Building A Duty',
  'Waka Humas': 'Vice Principal of Public Relations',
  'Pembina Kedisiplinan Siswa': 'Student Discipline Advisor',
  'Pembina IRMA': 'IRMA Advisor',
  'BK & Piket Gedung C': 'Counselor & Building C Duty',
  'Waka Kesiswaan': 'Vice Principal of Student Affairs',
  'Pembina OSIS': 'Student Council Advisor',
  'SARPRAS': 'Facilities & Infrastructure',
  'BK & Piket Gedung D & E': 'Counselor & Buildings D & E Duty',
  'Kepala IT': 'Head of IT',
  'Medsos': 'Social Media',
  'Media Kreatif': 'Creative Media',
  'Desain Grafis': 'Graphic Design',
  'Server': 'Server',
  'Teknisi': 'Technician',
  'KA TU Keuangan': 'Head of Finance Administration',
  'Staff TU Keuangan': 'Finance Administration Staff',
  'Admin Kurikulum & Keuangan': 'Curriculum & Finance Admin',
  'Bendahara BOS': 'BOS Fund Treasurer',
  'Kepala TU & DAPODIK': 'Head of Administration & DAPODIK',
  'Logistik': 'Logistics',
  'Admin Keguruan': 'Teacher Affairs Admin',
  'Admin Kesiswaan': 'Student Affairs Admin',
  'Perpustakaan': 'Library',
  'Seragam, BTBA & Piket Gedung D': 'Uniforms, BTBA & Building D Duty',
  'Seragam, BTBA & Piket Gedung E': 'Uniforms, BTBA & Building E Duty',
};
